### PR TITLE
rename file to reads_ifs

### LINKED ISSUE #26: Segfault when running with process substitution on MacOS
Not sure if this is worth investigating, but flexiplex seems to fail with segfault when running with process substitution on MacOS:
`./flexiplex -e 2 -f 8 -k <(curl -sL https://raw.githubusercontent.com/mritchielab/FLAMES/devel/inst/extdata/bc_allow.tsv.gz | zcat) <(curl -sL https://raw.githubusercontent.com/mritchielab/FLAMES/devel/inst/extdata/fastq/musc_rps24.fastq.gz | zcat)`
This could be reproduced from commit 27194e9 .
I can't do backtrace and debugging with the WEHI managed laptop.

### PR DESCRIPTION
**Pull request by ChangqingW**
fix #26

### CODE REVIEW

**Comment by olliecheng** [comment]
Ahh you beat me to it! Was just about to push the exact same commit!

**Comment by olliecheng** [comment]
Not sure why, because reuse of an ifstream after closing _should_ be OK. Would be curious if RAII is getting overaggressive, possibly due to the use of a pointer..?

**Comment by ChangqingW** [comment]
Yeah how that happened is totally beyond me, this reusing of it did not throw segfault error when both are actual files, did not throw when the second is a file from `/dev/fd`, but throws when both are from `/dev/fd` 🤷

**Comment by olliecheng** [comment]
Yep. Don't really know C++ well enough to comment on how file.close works! I'm happy to merge this if you are?

**Comment by olliecheng** [comment]
Ah, just checked. After closing, `file.fail()` is set to 1. So yes, it's a temporary file closing issue.

**Pull request merged**
